### ISSUE TITLE
search_lightcurve unexpectedly can't find data

### ISSUE THREAD

**Issue by bmorris3** [lightkurve/lightkurve#1355] opened 2023-08-07 13:04 UTC
#### Problem description

I've been using the following line of code for months without issue:
```python
from lightkurve import search_lightcurve

lc_q9 = search_lightcurve("HAT-P-11", mission="Kepler", cadence="long", quarter=9).download()
```
but today it returns `None` and warns: `No data found for target "HAT-P-11".`

#### Expected behavior

This used to return the Q9 Kepler observations.

#### Environment

-  platform (e.g. Linux, OSX, Windows): OS X 12.6
-  lightkurve version (e.g. 1.0b6): 2.4.1dev
-  installation method (e.g. pip, conda, source): source

**Comment by bmorris3** [comment] 2023-08-07 13:14
Searching for these specific observations via the MAST portal is returning no observations today:
<img width="2090" alt="Screen Shot 2023-08-07 at 09 08 28" src="https://github.com/lightkurve/lightkurve/assets/3497584/fd3a2174-154b-4ffc-8692-07324135946b">

I've submitted a MAST help desk ticket. I'll respond here and close this issue when it's resolved!

**Comment by rebekah9969** [comment] 2023-08-07 14:59
Hello @bmorris3 

Thank you for your email. I am also able to reproduce your issue. Please let us know what MAST says when you hear back. 

Thanks again.

**Comment by retifrav** [comment] 2023-08-07 17:53
Hah, I thought I've gone crazy, because just two days ago my scripts were working fine, but yesterday I suddenly started getting no results for my queries to MAST. Thank you for reporting this here and with the MAST helpdesk. Yes, please do let us know if you get any response.

**Comment by scfleming** [comment] 2023-08-07 19:56
Update: the name resolving should work correctly for this target now.

**Comment by Hiyabiswas** [comment] 2023-08-08 11:55
When I type this command:
sector_data = lk.search_lightcurve(TIC, author = 'SPOC')

this is showing:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 sector_data = lk.search_lightcurve(TIC, author = 'SPOC')

AttributeError: module 'lightkurve' has no attribute 'search_lightcurve'

**Comment by rebekah9969** [comment] 2023-08-08 14:10
@Hiyabiswas What is the TIC ID you are querying here please?

**Comment by Hiyabiswas** [comment] 2023-08-08 14:14
TIC 236887394 for Qatar-1b

**Comment by rebekah9969** [comment] 2023-08-08 14:34
@Hiyabiswas your issue has now moved to #1356 please see this for further discussion.

**Closed** 2023-08-08 15:16 UTC
