### ISSUE TITLE
CBVcorrector.correct() not working for K2 data

### ISSUE THREAD

**Issue by maddyhowell** [lightkurve/lightkurve#1008] opened 2021-03-22 01:04 UTC
I am trying to use the CBVcorrector for data from the K2 mission (campaign 2). I am able to make the CBVcorrector for my light curve, however when I try to use CBVCorrector(lc).correct() it has an error of 'Unknown mission'.

I noticed that on line 592 in the CBVcorrector.py file https://github.com/lightkurve/lightkurve/blob/f22f351aa51ca01d7bc39cb8fa1f7efa35e745fb/src/lightkurve/correctors/cbvcorrector.py#L592

Should this be written as: 
```
elif (self.lc.mission == 'Kepler' or self.lc.mission == 'K2'):
```
So it identifies light curves from the K2 mission?

**Comment by barentsen** [comment] 2021-03-22 16:39
Thank you for reporting this issue @maddyhowell!

/cc @jcsmithhere would you be willing to have a look?

**Comment by jcsmithhere** [comment] 2021-03-22 21:21
Yes, I can take a look. That does indeed look like a bug! I have tested CBVCorrector on K2 data. Could you give an example to generate the above error?

**Comment by maddyhowell** [comment] 2021-03-22 23:37
Here is an example:


```python
from lightkurve import KeplerTargetPixelFile
import numpy as np
from lightkurve.correctors import CBVCorrector

tpf = KeplerTargetPixelFile('http://archive.stsci.edu/missions/k2/target_pixel_files/c2/200000000/04000/ktwo200004373-c02_lpd-targ.fits.gz')
 
# tpf cutout of star
tpf_cut = tpf.cutout((31.63824163918389 + 1, 12.268426085397477 + 1), size = 6)

# create example aperture mask
ap_mask = np.zeros(tpf_cut.shape[1:], dtype=np.int)
ap_mask[:] = False
ap_mask[2][1:5] = True
ap_mask[3][1:5] = True
ap_mask = ap_mask.astype(bool)

# light curve from aperture mask
lc_ap = tpf_cut.to_lightcurve(aperture_mask = ap_mask)
print("Mission:", lc_ap.mission) # check mission of light curve is K2 

# CBV corrector
cbv = CBVCorrector(lc_ap)
lc_cbv = cbv.correct()
```
This produces the error 'Unknown mission' at the last line of the above code. I have included a check to see what the light curve's mission was, which returns 'K2' as expected.

**Comment by jcsmithhere** [comment] 2021-03-23 07:19
Thanks, this certainly looks like a bug. I hope to get to the fix this week.

**Comment by jcsmithhere** [comment] 2021-03-24 07:53
Hi @maddyhowell, OK, this was indeed the bug exactly as you suggested. It's fixed in PR#1012. However, if you do not want to wait for the PR to get merged you can simply make the change just as you recommended above.

I should also note that the default correct() method for your example target does not perform well:

```
lc_cbv = cbv.correct()
pltAxis = cbv.diagnose()
pltAxis[0].set_ylim(2.0e5, 2.2e5);
pltAxis[1].set_ylim(2.0e5, 2.2e5);
```
![Screenshot from 2021-03-24 00-45-40](https://user-images.githubusercontent.com/6098349/112273173-48a9a000-8c3a-11eb-8f23-75fc1faecf05.png)


You can see the correction severely underfits, as the over/underfitting metrics show:

```
cbv.goodness_metric_scan_plot();
```
![Screenshot from 2021-03-24 00-46-14](https://user-images.githubusercontent.com/6098349/112273248-5c550680-8c3a-11eb-8d2b-05fb201beaec.png)

I would recommend a correction more like this to remove the K2 roll motion sawtooth:

```
lc_cbv = cbv.correct_gaussian_prior(alpha=1.0e-3)
pltAxis = cbv.diagnose()
pltAxis[0].set_ylim(2.05e5, 2.13e5);
pltAxis[1].set_ylim(2.05e5, 2.13e5);
```

![Screenshot from 2021-03-24 00-46-59](https://user-images.githubusercontent.com/6098349/112273327-77c01180-8c3a-11eb-9524-cb2fc30cd848.png)

However, be careful, there appears to be no simple ridge regression fit that performs well with both overfitting and underfitting. CBVCorrector, and the CBVs it's based on, was never really tuned well for K2 data.  PLDCorrector or SFFCorrector may work better for this target.

**Comment by maddyhowell** [comment] 2021-03-24 08:34
Thank you for your help!

**Closed** 2021-03-24 14:49 UTC

**Comment by barentsen** [comment] 2021-03-24 14:53
The fix has been merged into the `main` branch and will be part of Lightkurve v2.0.7, to be released on pypi in the next ~day!

**Comment by barentsen** [comment] 2021-03-24 22:14
v2.0.7 has been released on pypi now.  Please try again!
