### ISSUE TITLE
showing key error "data URL" while trying to download  a targetpixelfile

### ISSUE THREAD

**Issue by CelestialWood** [lightkurve/lightkurve#1381] opened 2023-11-02 03:05 UTC
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 5
      1 import lightkurve as lk
      2 from lightkurve import search_targetpixelfile
----> 5 pixelFile = search_targetpixelfile('TIC 419012256').download()
      6 lc = pixelFile.to_lightcurve()
      7 lc.plot()

File ~\anaconda3\Lib\site-packages\lightkurve\utils.py:566, in suppress_stdout.<locals>.wrapper(*args, **kwargs)
    564 sys.stdout = devnull
    565 try:
--> 566     return f(*args, **kwargs)
    567 # restore to default
    568 finally:
    569     sys.stdout = old_out

File ~\anaconda3\Lib\site-packages\lightkurve\search.py:432, in SearchResult.download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    422 if len(self.table) != 1:
    423     warnings.warn(
    424         "Warning: {} files available to download. "
    425         "Only the first file has been downloaded. "
   (...)
    429         LightkurveWarning,
    430     )
--> 432 return self._download_one(
    433     table=self.table[:1],
    434     quality_bitmask=quality_bitmask,
    435     download_dir=download_dir,
    436     cutout_size=cutout_size,
    437     **kwargs,
    438 )

File ~\anaconda3\Lib\site-packages\lightkurve\search.py:351, in SearchResult._download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    348 else:
    349     from astroquery.mast import Observations
--> 351     download_url = table[:1]["dataURL"][0]
    352     log.debug("Started downloading {}.".format(download_url))
    353     download_response = Observations.download_products(
    354         table[:1], mrp_only=False, download_dir=download_dir
    355     )[0]

File ~\anaconda3\Lib\site-packages\astropy\table\table.py:1872, in Table.__getitem__(self, item)
   1870 def __getitem__(self, item):
   1871     if isinstance(item, str):
-> 1872         return self.columns[item]
   1873     elif isinstance(item, (int, np.integer)):
   1874         return self.Row(self, item)

File ~\anaconda3\Lib\site-packages\astropy\table\table.py:246, in TableColumns.__getitem__(self, item)
    236 """Get items from a TableColumns object.
    237 ::
    238 
   (...)
    243   tc[1:3] # <TableColumns names=('b', 'c')>
    244 """
    245 if isinstance(item, str):
--> 246     return OrderedDict.__getitem__(self, item)
    247 elif isinstance(item, (int, np.integer)):
    248     return list(self.values())[item]

KeyError: 'dataURL'

**Comment by orionlee** [comment] 2023-11-02 23:30
Essentially a duplicate of #1377 .

#1377 talks about downloading lightcurve files but the underlying issue applies to targetpixelfile.

An interim workaround, before either `lightkurve` has a new release or MAST fixed its issue.

```python
sr = lk.search_targetpixelfile('TIC 419012256')
sr.table["dataURL"] = sr.table["dataURI"]  # workaround MAST issue
tpf = sr.download()
```

**Closed by orionlee** 2023-11-02 23:30 UTC
