### ISSUE TITLE
recovered transit depth of known planet off by order of magnitude for dim host star in TESS FFI

### ISSUE THREAD

**Issue by billy210** [lightkurve/lightkurve#1341] opened 2023-06-02 20:35 UTC
#### Problem description
I was testing out my lightkurve script to make sure I was recovering known planets at a range of magnitudes found in TESS FFIs while using the PLD corrector, and ran into an issue with TOI-2406. While trying to recover TOI-2406b I was able to accurately recover the period, but the transit depth was nearly an order of magnitude less than the known value, and the baseline scatter is also much lower than whats been reported in the literature. Is the PLD corrector known to reduce the scatter by this much for dim stars? 

#### Example

```python
search_resultstar= lk.search_tesscut('TIC 212957629',sector=3)
tpf_cutoutstar = search_resultstar.download(cutout_size=(10,10))
cut_mask = np.zeros(tpf_cutoutstar[0].shape[1:], dtype='bool')

cut_mask[4,6] = True
cut_mask[4,5] = True
cut_mask[5,6] = True
cut_mask[5,5] = True
cut_mask[5,4] = True
cut_mask[6,5] = True
cut_mask[4,4] = True
cut_mask[6,4] = True
cut_mask[6,6] = True

pld = PLDCorrector(tpf_cutoutstar,aperture_mask=cut_mask)
pld_corrected_lcstar = pld.correct(restore_trend=False, pca_components=5, pld_aperture_mask=cut_mask,pld_order=1)

pld_corrected_lcstar.normalize().scatter()
```
![image](https://github.com/lightkurve/lightkurve/assets/23263442/3e2d6746-74af-41e4-94bc-1cb1a4ba220c)

#### Expected behavior
The scatter seen in the literature is closer to +- 0.02 rather than the +-0.002 I'm seeing from the lightkurve output. 

#### Environment

-  platform (Linux):
-  lightkurve version (2.4.1dev):
-  installation method (git clone):

**Comment by rebekah9969** [comment] 2023-06-07 22:58
Hello @billy210,

To better assist you with this issue could you please state what paper data (i.e., the literature) you are referring to?

Thank you

**Comment by billy210** [comment] 2023-06-08 15:09
Hi Rebekah, 

The paper results I was comparing to was Wells et al. (2021) https://www.aanda.org/articles/aa/pdf/2021/09/aa41277-21.pdf

**Comment by rebekah9969** [comment] 2023-06-15 19:42
Dear @billy210,

Once again thank you for your posting this issue.

We have looked into your issue and note the following problems:

1. There is a bug in the PLDCorrector class where the background is not removed from your data and it is not informing you of this. This bug will be fixed by our team and we thank you for drawing our attention to it.

2. From the code posted above we can see that you are applying the PLDCorrector to a TESSCut TPF. The PLDCorrector works on background subtracted TPFs (e.g., median background subtracted products), not the TESSCut TPF you have created which still has its background. We note that there is a TESS-SPOC TPF for your object of interest in Sector 3 which you could use,  however this brings us to point 3.

3. In general the PLDCorrector is not suitable crowded data and is not recommended for TESS data except in the brightest not crowded cases. Pixel Level Deceleration (PLD) works by identifying a set of trends in the pixels surrounding the target star, and performing linear regression to create a combination of these trends that effectively models the noise. This noise model is then subtracted from the uncorrected light curve. A crowded field will mean that you are creating an inaccurate model and as such your reduced light curve will be unreliable.

We hope that this addresses your concern and we will work to fix the bug asap.

**Comment by billy210** [comment] 2023-06-19 19:18
Hi @rebekah9969 ,

Thank you for the update! A final question just to make sure I understand correctly: would it therefore be correct to assume that none of the lightkurve correctors should be used on TESSCut FFI files in crowded regions (especially for dim stars), or that the PLD corrector specifically should not be used?

**Comment by christinahedges** [comment] 2023-09-06 18:08
@billy210 it looks like this issue has been resolved, I'm closing this now, if you require any more help please feel free to comment here or email us at [tesshelp@bigbang.gsfc.nasa.gov](tesshelp@bigbang.gsfc.nasa.gov).

**Closed by christinahedges** 2023-09-06 18:08 UTC
Labels: :bug: bug, :sos: helpdesk
