### ISSUE TITLE
Multithreading!

### ISSUE THREAD

**Issue by 0J3lack0** [lightkurve/lightkurve#1240] opened 2022-07-11 13:07 UTC
I am using Lightkurve library for multiple star data. I am quite satisfied, but it would be very useful to have a multithreading feature. "lightcurve.Bin" and frequency analysis takes quite a long time. Is there a way to run these functions multithread? Or are you considering adding this feature?

**Comment by orionlee** [comment] 2022-07-11 21:18
1. `Lightcurve.bin()` is very slow primarily because of a performance regression in the underlying Astropy library. See #1190 for details.

Ways to improve the performance:
- downgrade to  lightkurve v2.0.11 + astropy v4.3.1  (basically astropy < 5.0)
- bin only the columns you care about , e.g., if you only care about `flux`/`flux_err`, do :
```python
lc_binned = lc["time", "flux", "flux_err"].bin(time_bin_size = 10 * u.min)
```

2. On frequency analysis: Lightkurve's `Periodogram` is primarily a convenient wrapper over the Astropy's Lomb-Scargle Periodograms / Box Least Squares (BLS) Periodogram. One could consult Astropy's documentation. Some of the parameters could have noticeable impact on performance.

https://docs.astropy.org/en/stable/timeseries/index.html#periodogram-algorithms

---

Lastly, it sounds like you are working on a batch of stars. While there is no multi-threaded support at this point, you could probably get similar benefits by running the analysis in multiple processes.

**Comment by 0J3lack0** [comment] 2022-07-15 23:17
**_Thank you very much for your reply._** It worked! I'm reviewing the document you specified for frequency analysis. I hope I can make it. At this point, my goal is to determine the frequencies in the light curve as we determined in the Peroid04 software. I will do this for thousands of stars. That's why I need a fully automated system I'm working on. I'm working with a library called Pyriod, but its author didn't develop it for this kind of work. I will meet with him. **Thanks again for your help.**

**Comment by ZRupp** [comment] 2022-07-26 18:09
`lc_binned = lc["time", "flux", "flux_err"].bin(time_bin_size = 10 * u.min)` does not work for me.  When I try, it throws the following error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [66], in <cell line: 1>()
----> 1 lc_binned = lc["time", "flux", "flux_err"].bin(time_bin_size = 10 * astropy.units.min)

File ~\anaconda3\lib\site-packages\astropy\utils\decorators.py:546, in deprecated_renamed_argument.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    543             msg += f'\n        Use {alternative} instead.'
    544         warnings.warn(msg, warning_type, stacklevel=2)
--> 546 return function(*args, **kwargs)

File ~\anaconda3\lib\site-packages\lightkurve\lightcurve.py:1549, in LightCurve.bin(self, time_bin_size, time_bin_start, time_bin_end, n_bins, aggregate_func, bins, binsize)
   1546 with warnings.catch_warnings():
   1547     # ignore uninteresting empty slice warnings
   1548     warnings.simplefilter("ignore", (RuntimeWarning, AstropyUserWarning))
-> 1549     ts = aggregate_downsample(
   1550         self,
   1551         time_bin_size=time_bin_size,
   1552         n_bins=n_bins,
   1553         time_bin_start=time_bin_start,
   1554         aggregate_func=aggregate_func,
   1555         **kwargs
   1556     )
   1558     # If `flux_err` is populated, assume the errors combine as the root-mean-square
   1559     if np.any(np.isfinite(self.flux_err)):

File ~\anaconda3\lib\site-packages\astropy\timeseries\downsample.py:98, in aggregate_downsample(time_series, time_bin_size, time_bin_start, time_bin_end, n_bins, aggregate_func)
     95     time_bin_end = Time(time_bin_end)
     97 # Use the table sorted by time
---> 98 ts_sorted = time_series.iloc[:]
    100 # If start time is not provided, it is assumed to be the start of the timeseries
    101 if time_bin_start is None:

File ~\anaconda3\lib\site-packages\astropy\table\index.py:940, in TableILoc.__getitem__(self, item)
    938 else:
    939     key = self.table.primary_key
--> 940 index = self.indices[key]
    941 rows = index.sorted_data()[item]
    942 table_slice = self.table[rows]

File ~\anaconda3\lib\site-packages\astropy\table\index.py:796, in TableIndices.__getitem__(self, item)
    793     # index search failed
    794     raise IndexError(f"No index found for {item}")
--> 796 return super().__getitem__(item)

TypeError: list indices must be integers or slices, not NoneType`

Without selecting only those columns it works, but it is very slow. Even when leveraging multiprocessing, doing this in batches is still very slow.

**Comment by christinahedges** [comment] 2023-04-07 17:22
@0J3lack0 and @ZRupp thank you for opening this issue and discussing this. We're aware that the `bin` function is very slow and we're going put some work into addressing that next month. I'm going to close this issue for now, but please watch this space!

**Closed by christinahedges** 2023-04-07 17:22 UTC
