### ISSUE TITLE
Having Trouble with lc.download for various stars trying to download TESS-SPOC data

### ISSUE THREAD

**Issue by jzverch** [lightkurve/lightkurve#1385] opened 2023-11-10 18:51 UTC
#### Problem description

I am having trouble pulling the light curves for certain stars in the TESS/TESS-SPOC database. I have dowloaded multiple files using the python script, in combination with several of the lightkurve commands. But for some reason my professor and I are having trouble extracting and downloading the light curves for certain TIC ####### stars. I have multiple sectors and cadences for some stars and he has the same information for other stars. All of the stars in our list print the table, but we try to download the data, we are unable to. It presents us with the same issue for varying stars. We are using the same script both on Mac. but he has some stars I can't download the information for. It has something to do with the DATA_URL with lightkurve. I will post the code we use below, and the error we are getting when trying to download the light curve data for these stars. If I need to elloborate some more please let me know anyhelp is appreciated as this is just now occuring and i have been using lightkurve to download the data for various stars the last few months. It could be something as si mple as a line, or not having the right version of lightkurve installed. I am just not sure,

#### Example
import lightkurve as lk
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
star="TIC 425819615" # substitute ???? for you specific TIC number
#pd.options.display.max_rows=100
data=lk.search_lightcurve(star)
data

# Extract the table from the SearchResult object
table = data.table

# Define the columns you want to display
columns_to_display = ['mission', 'year', 'author', 'exptime', 'target_name']

# Create a Pandas DataFrame with the selected columns
df = table[columns_to_display].to_pandas()

# Display the entire DataFrame
pd.set_option('display.max_rows', None)  # Show all rows
print(df)
lc = data[1].download()  # substitute ? for a specific dataset you want to download
lc

# Error when getting to lc = data[1].download()

KeyError                                  Traceback (most recent call last)
Cell In[21], line 1
----> 1 lc = data[1].download()  # substitute ? for a specific dataset you want to download
      2 lc

File ~/anaconda3/lib/python3.11/site-packages/lightkurve/utils.py:566, in suppress_stdout.<locals>.wrapper(*args, **kwargs)
    564 sys.stdout = devnull
    565 try:
--> 566     return f(*args, **kwargs)
    567 # restore to default
    568 finally:
    569     sys.stdout = old_out

File ~/anaconda3/lib/python3.11/site-packages/lightkurve/search.py:432, in SearchResult.download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    422 if len(self.table) != 1:
    423     warnings.warn(
    424         "Warning: {} files available to download. "
    425         "Only the first file has been downloaded. "
   (...)
    429         LightkurveWarning,
    430     )
--> 432 return self._download_one(
    433     table=self.table[:1],
    434     quality_bitmask=quality_bitmask,
    435     download_dir=download_dir,
    436     cutout_size=cutout_size,
    437     **kwargs,
    438 )

File ~/anaconda3/lib/python3.11/site-packages/lightkurve/search.py:351, in SearchResult._download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    348 else:
    349     from astroquery.mast import Observations
--> 351     download_url = table[:1]["dataURL"][0]
    352     log.debug("Started downloading {}.".format(download_url))
    353     download_response = Observations.download_products(
    354         table[:1], mrp_only=False, download_dir=download_dir
    355     )[0]

File ~/anaconda3/lib/python3.11/site-packages/astropy/table/table.py:1872, in Table.__getitem__(self, item)
   1870 def __getitem__(self, item):
   1871     if isinstance(item, str):
-> 1872         return self.columns[item]
   1873     elif isinstance(item, (int, np.integer)):
   1874         return self.Row(self, item)

File ~/anaconda3/lib/python3.11/site-packages/astropy/table/table.py:246, in TableColumns.__getitem__(self, item)
    236 """Get items from a TableColumns object.
    237 ::
    238 
   (...)
    243   tc[1:3] # <TableColumns names=('b', 'c')>
    244 """
    245 if isinstance(item, str):
--> 246     return OrderedDict.__getitem__(self, item)
    247 elif isinstance(item, (int, np.integer)):
    248     return list(self.values())[item]

KeyError: 'dataURL'
#### Expected behavior

Downloading the respective light curve data for the sector that is specified in the table. That way we can move foward with extracting the Time and Flux values. 

#### Environment

-  Code is compiled using jupyter lab
-  using latest lightkurve version (e.g. 1.0b6):
-  lightkurve was installed using pip

**Comment by jzverch** [comment] 2023-11-10 19:43
I made sure the lightkurve is up to date. Now that its up to date i was able to download one of the stars. I am going to try and download more sectors and see what happens.

**Comment by Nschanche** [comment] 2023-11-14 19:26
Hi @jzverch , this is a recent issue that was caused by a change to the MAST search. A new update was put out last week, so it should work with version 2.4.2. I'll close this issue now, but if you have further problems, you can open this issue back up.

**Closed** 2023-11-14 19:28 UTC
