### ISSUE TITLE
tpf.interact() problem. Only the bottom row of pixels are selectable.

### ISSUE THREAD

**Issue by PersonyPerson-KoD** [lightkurve/lightkurve#1142] opened 2021-09-21 18:09 UTC
Hello

Just a heads up. I'm not very experienced in coding, so there is probably a very simple solution to this that I am missing. I've only started using the software properly within the last week. But I couldn't find a solution so I decided to create this issue.
#### Problem description

I recently reinstalled Lightkurve after problems with trying to install another programme (tessLATTE). When using tpf.interact to check the lightcurves of individual pixels I can only select the bottom row of pixels. This happens regardless of what TIC object I put in.

As I initially thought it was a problem caused by the failures of trying to install that software. But I then tried to install it on my other PC with a Fresh install of Annaconda, Jupyter Notebook and Lightkurve and still encountered the same issue, so I came to the conclusion it is a problem with one of them in some form.
#### Example

```python
In [1]:
import lightkurve as lk

In [2]:
search_result = lk.search_targetpixelfile('TIC 335917092', sector=40)
search_result

In [3]:
tpf = search_result[0].download()

In [4]:
tpf.interact()
```

#### Expected behavior

Normally I should be able to select all of the pixels and view their light curves. But only the the bottom row of pixels are selectable: [https://imgur.com/P8t8rqK.png](url)

It worked beforehand from which I was using older versions of Annaconda and Jupyter Notebook (At least 2 years old). However when messing around with trying to install tessLATTE (Which I don't think is compatible with Windows), I installed newer versions of them along with many modules and packages and have now encountered this problem.
#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): 2.0.10
-  installation method (e.g. pip, conda, source): pip, but through Annaconda. I then use lightkurve through Jupyter Notebook.

**Comment by benjaminpope** [comment] 2021-09-28 05:50
Hi Lightkurve team, having the same problem! Using latest lk and bokeh 2.2.3.

**Comment by jcsmithhere** [comment] 2021-10-15 23:31
I get the same error in Lightkurve version 2.0.12dev (main HEAD).

**Environment**
- platform: Linux
- lightkurve version: 2.0.12dev
- installation method : source
- jupyterlab: 3.0.11
- matplotlib: 3.3.4

**Comment by gully** [comment] 2021-11-01 18:57
Hi all, this looks like a duplicate of #990 
The current workaround is to [downgrade to bokeh 2.2.3](https://github.com/lightkurve/lightkurve/issues/990#issuecomment-891199151)

There is a prototype solution to the problem that would allow lightkurve to work with versions of bokeh 2.3+ here at #1057.  If anyone has the stomach for beta-testing and modifying that PR, it would solve this problem.  I just marked it as "ready for review" despite needing some more work.  Is anyone here open to helping with it?

**Comment by PersonyPerson-KoD** [comment] 2021-11-01 19:43
Thank you. The downgrade workaround worked for me.

Apologies for duplicating the issue. Must have missed it when I was looking for a similar thread to the one I created.

Unfortunately I am not knowledgeable enough to do such beta testing. Hopefully others who are can to help you fix the issue once and for all.

**Comment by orionlee** [comment] 2022-06-25 00:10
Closing the issue as it's been fixed.

**Closed by orionlee** 2022-06-25 00:10 UTC
