### ISSUE TITLE
Better caching for CBVCorrector

### ISSUE THREAD

**Issue by bmorris3** [lightkurve/lightkurve#1159] opened 2021-11-09 14:37 UTC
Thanks again for this great package.

It appears that the current implementation of `CBVCorrector` searches MAST for a target with a matching name, then searches the local caches for the CBVs. It seems not to cache the result of the name lookup step. As a result, when `archive.stsci.edu` goes down, the `CBVCorrector` command appears to be attempting a name lookup, failing, and then timing out, even though the data are locally available. 

Would it be possible to skip/cache that name lookup step as well to avoid relying on the MAST webpage? This unfortunate unreliability of MAST is propagating into lightkurve and breaking one of my pipelines intermittently. 

If this is possible,  and you could point me to the place in the source where this change might be made, I'd be happy to put together a PR. I think [this is the relevant bit](https://github.com/lightkurve/lightkurve/blob/bb0d4546d072e51a267c02a233f563548ee06a3b/src/lightkurve/correctors/cbvcorrector.py#L1790-L1793) but I'm not positive. 

Thanks!

**Comment by jcsmithhere** [comment] 2021-11-10 07:34
Hi @bmorris3! Thanks for the feedback and the recommendation. This is a good idea. 

In the code around where you pointed, if you do not specify a `cbv_dir` then archive.stsci.edu is indeed searched for the CBVs, even if the CBVs are already cached locally. 

I suppose we would need to write some code to check if the appropriate CBV FITS files are already cached and then do not do the query. Both `load_kepler_cbvs` and `load_tess_cbvs` would need to be updated. 

You are welcome to work on this change. Note that there is a major change in CBVCorrector with PR #1155 that is to be merged soon. I also plan to do another PR soon to be able to load in the 30-minute FFI CBVs. These PRs touch `load_kepler_cbvs` and `load_tess_cbvs`. So, we will need to coordinate our merges.

**Comment by barentsen** [comment] 2021-11-10 18:42
@bmorris3 I'm sorry to hear you are experiencing those intermittent failures.  That sounds annoying!

It would be good to understand exactly which part of the CBV correction is failing intermittently.  I can think of two very different causes:

1. The failure may occur in the `load_kepler_cbvs`/`load_tess_cbvs`.  If `cbv_dir` is not supplied then the function will find the direct url to a CBV file via the download script (`https://archive.stsci.edu/missions/tess/download_scripts/sector/tesscurl_sector_{SECTOR}_cbv.sh`).  We could make this more robust via seamless caching, but I suspect this step is *not* to blame because it does not depend on the MAST Portal API and is fairly robust.
2. The failure may occur in the `metrics.underfit_metric_neighbors` function, which uses `search_lightcurve()` (via `lc.search_neighbors()`) to obtain neighboring light curves.  This step is more likely to fail intermittently because it depends on a query to the MAST Portal API and the subsequent data downloads.  The data downloads are cached in a persistent way, but the `search_lightcurve()` cache does not persist between Python processes yet.  There is a PR to address this (https://github.com/lightkurve/lightkurve/pull/1039).

...do save a stracktrace next time you encounter this intermittent failure, I expect it will show whether we need to address issue 1 or issue 2 first.

**Comment by christinahedges** [comment] 2023-04-07 17:50
Hi @bmorris3, it seems like this issue has been open for a while now, and I can't easily reproduce this failure. I'm going to close this issue for now, but if you find you are still encountering this issue please feel free to open it again and add the traceback and we'll take a look! 💪

**Closed by christinahedges** 2023-04-07 17:50 UTC
