### ISSUE TITLE
search_tesscut error under windows

### ISSUE THREAD

**Issue by sengle01** [lightkurve/lightkurve#1215] opened 2022-06-09 15:00 UTC
Hello,

When running search_tesscut I see a target has been observed in one or more sectors, but when I try to download tpfs in a jupyter notebook under windows I get the following error:

##############
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\lib\site-packages\lightkurve\search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    234                     download_dir,
--> 235                     cutout_size,
    236                 )

~\anaconda3\lib\site-packages\lightkurve\search.py in _fetch_tesscut_path(self, target, sector, download_dir, cutout_size)
    505         # this is necessary to ensure cutouts are not downloaded multiple times
--> 506         sec = TesscutClass().get_sectors(coords)
    507         sector_name = sec[sec["sector"] == sector]["sectorName"][0]

TypeError: get_sectors() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

SearchError                               Traceback (most recent call last)
<ipython-input-9-a1f97d3031c8> in <module>
----> 1 tpf = search_result_tpfs.download(cutout_size=20)

~\anaconda3\lib\site-packages\lightkurve\utils.py in wrapper(*args, **kwargs)
    553             sys.stdout = devnull
    554             try:
--> 555                 return f(*args, **kwargs)
    556             # restore to default
    557             finally:

~\anaconda3\lib\site-packages\lightkurve\search.py in download(self, quality_bitmask, download_dir, cutout_size, **kwargs)
    358             download_dir=download_dir,
    359             cutout_size=cutout_size,
--> 360             **kwargs,
    361         )
    362 

~\anaconda3\lib\site-packages\lightkurve\search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size, **kwargs)
    249                         "Unable to download FFI cutout. Desired target "
    250                         "coordinates may be too near the edge of the FFI."
--> 251                         "Error: {}".format(exc)
    252                     )
    253 

SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.Error: get_sectors() takes 1 positional argument but 2 were given
##################

However, there's no error when downloading them in a jupyter notebook under Linux. I've tried re-running the search_tesscut command with and without specifying sectors and the download error is always the same.

I've upgraded lightkurve in both. The Windows version is still 2.0.11 and the Linux version is 2.2.1. I'm not sure if that would be causing the error. 

Normally it would be fine to simply use Linux, but I also use lightkurve in class and students come in using different OSes so I'd rather

Best,
Scott

**Comment by sengle01** [comment] 2022-06-10 16:26
Here's an update to my own issue:

I was following the 'quickstart' instructions for installation and running

python -m pip install lightkurve

or 

python -m pip install lightkurve --upgrade

(depending on whether it was already installed)

The command worked perfectly fine on Linux, but on Windows it installed the older version. I just ran

conda install -c conda-forge lightkurve

and it installed lightkurve v2.1.1 which, although not the current version, was able to successfully download tpf files. 

So it seems this issue can be closed (unless perhaps documentation should be updated to include the caveat about installing within Windows - unless it's already in there somewhere but I missed it, in which case I'm very sorry for the bother!)

Best,
Scott

**Comment by barentsen** [comment] 2022-06-13 13:29
@sengle01 I'm sorry to hear you are experiencing this issue!

I believe the issue you encountered is caused by using `lightkurve` <= v2.1.0 in combination with `astroquery` >= v0.4.6.

The `search_tesscut` features relies on Astroquery's `get_sectors` function, which changed in v0.4.6 of the Astroquery package (released in March 2022). Lightkurve v2.1.1 was released in the same month to account for this change, but as a result, `search_tesscut` requires Lightkurve v2.1.1 or later if Astroquery v0.4.6 is installed.

The question remains why you were unable to update Lightkurve in your Windows environment.  This is likely because Lightkurve v2.1.0 requires Python >=3.8 (previous versions required Python >=3.6).  This change was made because Lightkurve v2.1.0 requires Astropy v5.0, which in turn requires Python >=3.8.

*Conclusion: you will likely need to upgrade the Python installation in your Windows environment to Python >=3.8 first.  This will then enable you to installed Lightkurve v2.1.0 or later, which will resolve the `search_tesscut` issue you encountered.*

I hope this helps.  Upgrading Python packages and resolving conflicts between them can definitely be very frustrating!

**Comment by christinahedges** [comment] 2022-06-16 17:17
Hi @sengle01, it seems like @barentsen has written up a solution above, and @orionlee has written up a resolution of the same issue from other users (#1219) summarized in discussion post https://github.com/lightkurve/lightkurve/discussions/1224. I'm closing this issue now, if you still have an issue please feel free to post here and we'll get back to you.

**Closed by christinahedges** 2022-06-16 17:17 UTC
