### ISSUE TITLE
Issue with numpy through lightkurve

### ISSUE THREAD

**Issue by ashalexell** [lightkurve/lightkurve#1351] opened 2023-07-10 19:43 UTC
#### Problem description

Installed lightkurve and can not import due to an issue with numpy. Error message reads "AttributeError: module 'numpy' has no attribute 'float128'." 
#### Example

```python
import lightkurve

#### Expected behavior
<!-- Describe the behavior you expected and how it differs from the behavior observed in the example. -->
Supposed to import lightkurve with no issue and it doesn't
#### Environment

Windows-10-10.0.22621-SP0
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
astropy 5.1
numpy 1.23.5

installation method is through pip

**Comment by ashalexell** [comment] 2023-07-10 20:06
Here is the full traceback message:
Traceback (most recent call last):  File "<string>", line 1, in <module>  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\__init__.py", line 109, in <module>    from .correctors import *  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\correctors\__init__.py", line 19, in <module>    from .cbvcorrector import *  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\correctors\cbvcorrector.py", line 30, in <module>    from ..search import search_lightcurve  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\search.py", line 19, in <module>    from .targetpixelfile import TargetPixelFile  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\targetpixelfile.py", line 36, in <module>    from .prf import KeplerPRF  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\prf\__init__.py", line 2, in <module>    from .tpfmodel import *  File "C:\Users\oxfor\anaconda3\lib\site-packages\lightkurve\prf\tpfmodel.py", line 48, in <module>    from oktopus import Prior, GaussianPrior, UniformPrior, PoissonPosterior  File "C:\Users\oxfor\anaconda3\lib\site-packages\oktopus\__init__.py", line 3, in <module>    from .loss import *  File "C:\Users\oxfor\anaconda3\lib\site-packages\oktopus\loss.py", line 2, in <module>    import autograd.numpy as np  File "C:\Users\oxfor\anaconda3\lib\site-packages\autograd\__init__.py", line 2, in <module>    from .differential_operators import (  File "C:\Users\oxfor\anaconda3\lib\site-packages\autograd\differential_operators.py", line 16, in <module>    import autograd.numpy as np  File "C:\Users\oxfor\anaconda3\lib\site-packages\autograd\numpy\__init__.py", line 3, in <module>    from . import numpy_boxes  File "C:\Users\oxfor\anaconda3\lib\site-packages\autograd\numpy\numpy_boxes.py", line 52, in <module>    for type_ in [float, np.float128, np.float64, np.float32, np.float16,  File "C:\Users\oxfor\anaconda3\lib\site-packages\numpy\__init__.py", line 311, in __getattr__    raise AttributeError("module {!r} has no attribute "AttributeError: module 'numpy' has no attribute 'float128'. Did you mean: 'float16'?

    On Monday, July 10, 2023 at 02:44:34 PM CDT, github-actions[bot] ***@***.***> wrote:  
 
 


Hi there! 👋 Thank you for opening your first Lightkurve issue! 🙏 One of our maintainers will get back to you as soon as possible. 👩‍🚀 You can expect a response within 7 days. 📅 If you haven’t heard anything by then, feel free to ping this thread. 🛎️ We love that you are using Lightkurve and appreciate your feedback. 👍

**Comment by Nschanche** [comment] 2023-07-27 15:13
I was unable to reproduce this error using a Windows machine with the following configurations:

Windows-10-10.0.19045-SP0
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
lightkurve 2.4.0
astropy 5.3.1
numpy 1.25.1


Windows-10-10.0.19045-SP0
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
lightkurve 2.4.0
astropy 5.1
numpy 1.23.5

However, I see the error string involves the autograd package (autograd\numpy\numpy_boxes.py). This package was updated ~a month ago to change some of the float types, so perhaps updating this package will help with the import.

**Comment by ashalexell** [comment] 2023-07-27 17:58
I’m not sure if it’s relevant but I am running Windows 11 not windows 10On Jul 27, 2023, at 8:13 AM, Nschanche ***@***.***> wrote:﻿
I was unable to reproduce this error using a Windows machine with the following configurations:
Windows-10-10.0.19045-SP0
Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:47:18) [MSC v.1916 64 bit (AMD64)]
lightkurve 2.4.0
astropy 5.3.1
numpy 1.25.1
Windows-10-10.0.19045-SP0
Python 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
lightkurve 2.4.0
astropy 5.1
numpy 1.23.5
However, I see the error string involves the autograd package (autograd\numpy\numpy_boxes.py). This package was updated ~a month ago to change some of the float types, so perhaps updating this package will help with the import.

**Comment by gully** [comment] 2023-08-04 15:18
Hi @ashalexell, thanks for your interest in lightkurve and for reporting this friction point! 🙏 

I have encountered this bug in other contexts.  numpy deprecated all the `np.float` and `np.int` in favor of using the python built-in `float` and `int`.  The `np.float` conventions were so common that many of my codes broke in the same way.  Here is the [numpy release note about the deprecation](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

I think the solution to your problem would be to require an older version of numpy.  Since the change happend in numpy 1.20.0, I think anything before that should work.  Note that downgrading to an older numpy may be incompatible with other code you have installed, and so I recommend adopting best practices such as a sandboxed enviroment with `conda`, and many other good alternatives to conda exist.  Good luck on your problem.  

I will close this Issue since it appears we have identified the root cause, but if you think your issue is part of a broader problem with lightkurve, or we can provide better guidance in the install process, please to reopen the Issue.  Thanks again and good luck!

**Comment by gully** [comment] 2023-08-04 15:23
Whoops, two things, 
1) I notice that the error message is actually coming from autograd.  Are you attempting to combine autograd and lightkurve?  The problem may be catalyzed by autograd and not lightkurve.
2) I no longer have access to closing Issues, but I encourage you or other maintainers to close the Issue if you think it's resolved ☀️

**Comment by ashalexell** [comment] 2023-08-04 16:47
I have not tested it again. All I was doing was trying to import lightkurve. And I could not even import it. I still need to reset my numpy.Sent from my iPhoneOn Aug 4, 2023, at 9:23 AM, gully ***@***.***> wrote:﻿
Whoops, two things,

I notice that the error message is actually coming from autograd.  Are you attempting to combine autograd and lightkurve?  The problem may be catalyzed by autograd and not lightkurve.
I no longer have access to closing Issues, but I encourage you or other maintainers to close the Issue if you think it's resolved ☀️

**Comment by christinahedges** [comment] 2023-09-06 18:05
@ashalexell, we've been having some problems with `numpy` since their new version release, please try updating to the newest version of `lightkurve` which is 2.4.1. If you're still having trouble please report back and we'll open your issue again!

**Closed by christinahedges** 2023-09-06 18:05 UTC
