### ISSUE TITLE
Adjusting settings in plots

### ISSUE THREAD

**Issue by sourestdeeds** [lightkurve/lightkurve#946] opened 2021-02-12 01:55 UTC
Ive noticed that when trying to adjust figure sizes, its a bit difficult to access. Is there an easier way than using the ax object? A fold plot for example:
```python
ax = lc.fold(period=period) \
         .scatter(label=f'Period = {period.value:.3f} days', alpha=0.5)
```
Usually I set the plots up as follows:
```python
fig, ax = plt.subplots(figsize=(15,10))
```
Then access plt.plot(x, y) etc. What is the procedure lightkurve uses? Seaborn doesn't seem to override settings either.

**Comment by sourestdeeds** [comment] 2021-02-12 08:58
I think after a sleep I've realised I was too tired to get it working 😂

I think i understand what procedure to use now!

**Comment by barentsen** [comment] 2021-02-12 17:43
@sourestdeeds Thanks for reporting back.  Which solution did you end up using?

I can think of two options:

**Option 1:** Create your own axis and pass it on to lc.scatter() as follows:
```python
import lightkurve as lk
import matplotlib.pyplot as plt

lc = lk.search_lightcurve("Proxima Cen")[1].download()
fig, ax = plt.subplots(figsize=(3, 4))
lc.scatter(ax=ax)
```

**Option 2:** define your own matplotlib stylesheet file.  Lightkurve uses [lightkurve.mplstyle](https://github.com/lightkurve/lightkurve/blob/main/lightkurve/data/lightkurve.mplstyle) by default. You could edit this file and pass it into the plotting methods as follows:
```python
lc.scatter(style="/path/to/your/custom.mplstyle")
```

**Comment by sourestdeeds** [comment] 2021-02-13 22:56
Something along the lines of this works
```python
    fig, ax = plt.subplots(figsize=(15,15))
    ax=plt.subplot(311)
    plt.errorbar(lc.time, lc.flux,
                 lc.flux_err, color='b',
                 alpha=0.2, zorder=1, capsize=2, ls='none')
    plt.scatter(lc.time, lc.flux, color='k', s=0.5, alpha=0.6, zorder=2)
    plt.xlabel('Time (BTJD)')
    plt.ylabel('Flux')
    ax = subplot(...)
```
This also inherits from seaborn styles.

**Comment by barentsen** [comment] 2021-02-16 02:22
@sourestdeeds Thank you for posting this example.  Interesting to know this way works as well!

I bet other users will stumble on this thread/example in the future, which is great. :+1:

I will close this issue because I believe the problem is resolved, but feel free to reopen or create a new one if you have any more questions, or suggestions for improving this behavior!

**Closed by barentsen** 2021-02-16 02:22 UTC
